version: '3.8'

services:
  plex:
    image: linuxserver/plex:arm64v8-latest
    container_name: plex
    platform: linux/arm64  # for ARM-based images
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM}  # Your Plex claim token (optional)
      - ADVERTISE_IP=http://${HOST_IP}:32400/  # Replace HOST_IP with your network IP if needed
      - TZ=${TZ}  # Time zone
      - PLEX_UID=${PLEX_UID}  # User ID (for permissions)
      - PLEX_GID=${PLEX_GID}  # Group ID (for permissions)
    volumes:
      - ${PLEX_CONFIG_PATH}:/config  # Path for Plex configuration
      - ${PLEX_TRANSCODE_PATH}:/transcode  # Path for transcoding
      - ${PLEX_MEDIA_PATH}:/data  # Path for media files
    devices:
      - /dev/bus/usb:/dev/bus/usb
    restart: unless-stopped
    ports:
      - "32400:32400"  # Web interface
      - "3005:3005"    # Plex HTPC
      - "8324:8324"    # Plex DLNA
      - "32469:32469"  # Plex DLNA Discovery
      - "32410:32410/udp"  # GDM network discovery
      - "32412:32412/udp"  # GDM network discovery
      - "32413:32413/udp"  # GDM network discovery
      - "32414:32414/udp"  # GDM network discovery
      - "1900:1900/udp"    # SSDP
      - "32443:32443"      # Secure connections
      - "32400:32400/udp"  # Plex media server UDP

networks:
  default:
    driver: bridge
